// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/generate-i18n-resources.mjs

export const resources = {
  de: {
    'content': require('../locales/de/content.json'),
    'words': require('../locales/de/words.json'),
  },
  en: {
    'content': require('../locales/en/content.json'),
    'words': require('../locales/en/words.json'),
  },
  sk: {
    'content': require('../locales/sk/content.json'),
    'words': require('../locales/sk/words.json'),
  },
} as const;

export const SUPPORTED_LANGUAGES = ["de","en","sk"] as const;
export type Language = typeof SUPPORTED_LANGUAGES[number];