// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/generate-lesson-words.ts

import type { LessonId } from "@/app/models/lesson.model";
import type { TranslationKey } from "@/app/models/word.model";

export const LESSON_WORDS: Record<LessonId, readonly TranslationKey[]> = {
  "1": ["and", "no"],
  "2": ["yes"],
} as const;
