import fs from "fs";
import path from "path";

import { LESSON_WORD_RANGES } from "../app/content/lessonWordRanges";
import { type LessonId } from "../app/models/lesson.model";
import { type TranslationKey } from "../app/models/word.model";

const WORDS_JSON_PATH = path.resolve("app/locales/en/words.json");
const OUTPUT_PATH = path.resolve("app/content/lessonWords.generated.ts");

const raw = fs.readFileSync(WORDS_JSON_PATH, "utf-8");
const wordsJson = JSON.parse(raw) as Record<string, string>;

const allKeys = Object.keys(wordsJson) as TranslationKey[];

const lessonWords: Record<number, TranslationKey[]> = {};

let usedKeys = 0;

for (const [lessonIdRaw, range] of Object.entries(LESSON_WORD_RANGES)) {
  const lessonId = Number(lessonIdRaw) as LessonId;

  const { startIndex, wordCount } = range;

  const slice = allKeys.slice(startIndex, startIndex + wordCount);

  if (slice.length !== wordCount) {
    throw new Error(`Lesson ${lessonId}: expected ${wordCount} words, got ${slice.length}`);
  }

  lessonWords[lessonId] = slice;
  usedKeys += slice.length;
}

if (usedKeys > allKeys.length) {
  throw new Error("Used more words than exist in words.json");
}

const output = `
// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by scripts/generate-lesson-words.ts

import type { LessonId } from "@/app/models/lesson";
import type { TranslationKey } from "@/app/models/word";

export const LESSON_WORDS: Record<LessonId, readonly TranslationKey[]> = ${JSON.stringify(
  lessonWords,
  null,
  2,
)} as const;
`;

fs.writeFileSync(OUTPUT_PATH, output.trim() + "\n");

console.log("✔ lessonWords.generated.ts created");
